M48
; DRILL file {KiCad 8.0.2} date 2024-07-11T13:13:56+0200
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-07-11T13:13:56+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.2
; #@! TF.FileFunction,NonPlated,1,6,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0433
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0472
%
G90
G05
T1
X4.9928Y-1.4018
T2
X4.9928Y-3.1498
M30
